const { ethers } = require('ethers');
const fs = require('fs');
const path = require('path');
const config = require('../config');

// Blockchain service.
// In production, uses ethers.js to talk to the deployed EvidenceRegistry contract.
// For tests / local dev, you can set MOCK_BLOCKCHAIN=1 to use an in-memory mock.

const useMock = process.env.MOCK_BLOCKCHAIN === '1' || process.env.MOCK_BLOCKCHAIN === 'true';

let provider;
let contract;

// In-memory mock ledger when MOCK_BLOCKCHAIN is enabled
const mockLedger = new Map(); // fileHash -> record

function getContract() {
  if (useMock) return null;
  if (contract) return contract;

  const rpcUrl = config.chainRpcUrl;
  const address = config.contractAddress;
  if (!address) {
    throw new Error('CONTRACT_ADDRESS is not configured');
  }

  const deploymentPath = path.join(
    __dirname,
    '..',
    '..',
    'contracts',
    'deployment.json',
  );

  let abi;
  if (fs.existsSync(deploymentPath)) {
    const deployment = JSON.parse(fs.readFileSync(deploymentPath, 'utf8'));
    abi = deployment.abi;
  } else {
    // Fallback: try local ABI file (e.g., generated by Hardhat)
    const abiPath = path.join(
      __dirname,
      '..',
      '..',
      'contracts',
      'EvidenceRegistry.abi.json',
    );
    if (!fs.existsSync(abiPath)) {
      throw new Error('EvidenceRegistry ABI not found');
    }
    abi = JSON.parse(fs.readFileSync(abiPath, 'utf8'));
  }

  provider = new ethers.JsonRpcProvider(rpcUrl);
  contract = new ethers.Contract(address, abi, provider);
  return contract;
}

async function anchorEvidence({ fileHash, metadata, officerId }) {
  if (useMock) {
    const now = new Date().toISOString();
    const txHash = '0x' + fileHash.slice(0, 8) + 'mock';
    const blockNumber = Math.floor(Math.random() * 1_000_000) + 1;
    const record = {
      fileHash,
      transactionHash: txHash,
      blockNumber,
      anchoredAt: now,
      officerId,
      metadata,
    };
    mockLedger.set(fileHash, record);
    return record;
  }

  const c = getContract();
  const hashBytes32 = '0x' + fileHash;
  const tx = await c.anchorEvidence(hashBytes32, officerId, JSON.stringify(metadata || {}));
  const receipt = await tx.wait();

  const block = await provider.getBlock(receipt.blockNumber);
  const anchoredAt = new Date(Number(block.timestamp) * 1000).toISOString();

  return {
    fileHash,
    transactionHash: receipt.hash,
    blockNumber: receipt.blockNumber,
    anchoredAt,
    officerId,
    metadata,
  };
}

async function verifyEvidence(fileHash) {
  if (useMock) {
    const record = mockLedger.get(fileHash);
    if (!record) return { match: false, record: null };
    return { match: true, record };
  }

  const c = getContract();
  const hashBytes32 = '0x' + fileHash;
  const result = await c.verifyEvidence(hashBytes32);

  if (!result.exists) {
    return { match: false, record: null };
  }

  const record = {
    fileHash,
    transactionHash: result.transactionHash,
    blockNumber: Number(result.blockNumber),
    anchoredAt: new Date(Number(result.timestamp) * 1000).toISOString(),
    officerId: result.officer,
    metadata: JSON.parse(result.metadataJson || '{}'),
  };

  return { match: true, record };
}

async function linkStorage({ fileHash, storageCid }) {
  if (useMock) {
    const existing = mockLedger.get(fileHash);
    if (!existing) return;
    existing.storageCid = storageCid;
    mockLedger.set(fileHash, existing);
    return existing;
  }

  const c = getContract();
  const hashBytes32 = '0x' + fileHash;
  const tx = await c.linkStorage(hashBytes32, storageCid);
  const receipt = await tx.wait();
  return { transactionHash: receipt.hash, blockNumber: receipt.blockNumber };
}

module.exports = {
  anchorEvidence,
  verifyEvidence,
  linkStorage,
};

